site_name: terrys-toolbox
repo_url: https://github.com/tlg7c5/terrys-toolbox
site_url: https://tlg7c5.github.io/terrys-toolbox
site_description: A toolbox package to hold various tools with utility beyond a single repo.
site_author: Terry Garner
edit_uri: edit/main/docs/
repo_name: tlg7c5/terrys-toolbox
copyright: Maintained by tlg7c5.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tlg7c5/terrys-toolbox
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/terrys-toolbox

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.arithmatex:
      generic: true
